In [1]:
import pandas as pd 
import time
import json
import numpy as np

In [2]:
filename = 'indeed_'+time.strftime("%d-%m-%Y")+'.json'
df = pd.read_json(filename,orient='columns')

In [3]:
# df.sort_values('job_title',ascending=False)

In [4]:
df['job_title'].value_counts()

software engineer    55
data scientist       54
data analyst         53
Name: job_title, dtype: int64

In [5]:
df = df.drop_duplicates()
df.reset_index(drop=True, inplace=True)

In [6]:
df['job_title'].value_counts()

software engineer    40
data scientist       37
data analyst         37
Name: job_title, dtype: int64

In [7]:
# df['job_posting_salary'].value_counts()

In [8]:
df['job_posting_salary'] = df['job_posting_salary'].str.replace('\n', '')
df['job_posting_salary'] = df['job_posting_salary'].str.replace(',', '')
df['job_posting_salary'] = df['job_posting_salary'].str.replace('$', '')

In [9]:
df.head()

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date
0,"After, Inc.","After Inc., a leading provider of warranty/mar...",None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019
2,None,Reliable Software is looking for Jr. Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019
3,None,"$95,000 - $120,000 a yearSapphire Digital is l...",95000 - 120000 a year,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019

In [10]:
df['salary_period'] = 'None'
df['job_posting_salary'] = df['job_posting_salary'].fillna('None')
df.loc[(df['job_posting_salary'].str.contains("year")),'salary_period'] = 'year'
df.loc[(df['job_posting_salary'].str.contains("month")),'salary_period'] = 'month'
df.loc[(df['job_posting_salary'].str.contains("week")),'salary_period'] = 'week'
df.loc[(df['job_posting_salary'].str.contains("day")),'salary_period'] = 'day'
df.loc[(df['job_posting_salary'].str.contains("hour")),'salary_period'] = 'hour'

In [11]:
df.head()

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date,salary_period
0,"After, Inc.","After Inc., a leading provider of warranty/mar...",None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
2,None,Reliable Software is looking for Jr. Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
3,None,"$95,000 - $120,000 a yearSapphire Digital is l...",95000 - 120000 a year,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None

In [12]:
df['salary_period'].value_counts()

None    79
year    27
hour     8
Name: salary_period, dtype: int64

In [13]:
df["job_posting_salary"] = df["job_posting_salary"].str.replace(" a year", '')
df["job_posting_salary"] = df["job_posting_salary"].str.replace(" a month", '')
df["job_posting_salary"] = df["job_posting_salary"].str.replace(" a week", '')
df["job_posting_salary"] = df["job_posting_salary"].str.replace(" a day", '')
df["job_posting_salary"] = df["job_posting_salary"].str.replace(" an hour", '')

In [14]:
df

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date,salary_period
0,"After, Inc.","After Inc., a leading provider of warranty/mar...",None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
2,None,Reliable Software is looking for Jr. Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
3,None,"$95,000 - $120,000 a yearSapphire Digital is l...",95000 - 120000,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
5,AKCEA Therapeutics,"Ionis Pharmaceuticals, Inc., located in the No...",None,Clinical Data Scientist & Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
6,KAYAK,Position\n\nKAYAK is looking for people who lo...,None,Data Scientist (Labs),https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
7,IStream Solutions,*Duration: Contract to HireBackground: Data An...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None
8,NLB Corp,ContractAnalysis of large amounts of historica...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None
9,R2 Global AI,"$220,000 - $300,000 a yearPrincipal NLP Data S...",220000 - 300000,"Principle NLP Data Scientist, $220k-$300k, 40%...",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year
10,Daimler,Associate Software Engineer\nDescription\n\nMe...,None,Associate Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
11,"NVR, Inc",NVR has been helping families build their happ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
12,The Resource Connection,"$35 an hourTemporaryA state agency in Boston, ...",35,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour
13,Astral Technologies Inc,$70 an hourAstral Techs is searching for a Dat...,70,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,hour
14,Sperry Rail Inc.,$15 an hourVisual Data AnalystJoin the world l...,15,Visual Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour
15,AMGTech Solutions,"$60,000 - $70,000 a yearAMGTech Solutions is l...",60000 - 70000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
16,Perfectly Home Rugs,"$66,000 - $71,000 a yearWe are looking for ent...",66000 - 71000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
17,"Transdev Services, Inc.","$85,000 a yearThe Software & Database Speciali...",85000,Transit Software and Database Specialist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
18,HCL America,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
19,HCL Americas,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
20,"Terma North America, Inc.","Terma North America (TNA), the US subsidiary o...",None,Windows Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
21,SR Education Group,"$80,000 - $100,000 a yearSR Education Group’s ...",80000 - 100000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
22,HCL Americas,"$60,000 a yearJob Title – Entry Level Software...",60000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
23,Apple,"Summary\nPosted: Apr 2, 2019\nRole Number: 200...",None,"App Store Engineering, Software Engineer",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
24,Sky Highways,If you have 2 or more years software engineeri...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
25,Microsoft,Empower every person and organization on the p...,None,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
26,Dhatronictech,"$67,000 - $75,000 a yearWe have Entry Level So...",67000 - 75000,Entry level Software Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year
27,VisionWeb,Position Purpose: VisionWeb is looking for an ...,None,Software Development Engineer in Test,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
28,"Styles Logistics, Inc.",Position Description:We are looking for a Seni...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
29,"Jack Henry and Associates, Inc.",Are you someone who enjoys programming in C# a...,None,C# Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None
...,...,...,...,...,...,...,...,...,...
84,FINTRX,"$50,000 - $65,000 a yearJoin our growing team ...",50000 - 65000,Python Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,year
85,"Bojangles' Restaurants, Inc",We have an opportunity for an experienced and ...,None,Senior Business Insights Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None
86,21Tech,$60 - $80 an hourContractWe are looking for a ...,60 - 80,SQL Server Data Warehouse Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour
87,Viola AI,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
88,ANALYTOS,You will collaborate with the brightest techni...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
89,"CICONIX, LLC",Responsibilities and Duties\n\nModeling comple...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
90,Pluralsight,"Job Description\n\nAt Pluralsight, you will be...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
91,Urner Barry,JOB SUMMARY: The Data Scientist is part of the...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
92,The Hartford,Marketing Data Science\n\nThe Hartford seeks a...,None,"Data Scientist, Marketing",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
93,New York City Council,DUTIES AND RESPONSIBILITIESAre you excited by ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
94,Digitas,Job Description\n\nData & Analysis – Data Scie...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
95,Globant,We are a digitally native company where innova...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
96,Better.com,About Better:\nWe're one of the fastest growin...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
97,Reliant Technologies,Junior Data ScientistReliant Technologies is s...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
98,MRP,"$85,000 - $110,000 a yearA D.C. area company w...",85000 - 110000,Sr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year
99,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ub...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
100,"Amazon.com Services, Inc.","Masters in Analytics, Statistics, Operations R...",None,ACES Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
101,Honor,"Founded in 2015, Honor is now one of the faste...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
102,AETNA,POSITION SUMMARY\nPlease only use the job desc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
103,NEOGOV,We are looking for someone that possesses the ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
104,NYC Health + Hospitals,Clinical Data Scientist (Clinical Business Ana...,None,Clinical Data Scientist (Clinical Business Ana...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
105,"Audible, Inc.",Bachelors or MS or PhD in the following discip...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
106,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ma...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
107,Synchrony,"$85,000 - $170,000 a yearJob Description:\nRol...",85000 - 170000,"VP, Data Scientist",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year
108,Cengage,.\nDo you dare to reinvent the future of educa...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
109,Global Widget LLC (local Tampa Bay candidates ...,"$80,000 - $90,000 a yearData Scientist - Excel...",80000 - 90000,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year
110,FPT Software,Requires an extensive Data Science Education a...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
111,Medal,Welcome to MEDAL! We're making it easy to shar...,None,BioMedical Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
112,"Amazon.com Services, Inc.","Master's Degree in Computer Science, Mathemati...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None
113,American Institutes for Research,Overview\nWe are looking for a data scientist ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None

In [15]:
df['salary_lower'] = df["job_posting_salary"].str.split(" - ", n=1, expand=True)[0]
df['salary_upper'] = df["job_posting_salary"].str.split(" - ", n=1, expand=True)[1]

In [16]:
df['salary_lower']=df['salary_lower'].replace('None',0)
df['salary_upper']=df['salary_upper'].fillna(0)
df

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date,salary_period,salary_lower,salary_upper
0,"After, Inc.","After Inc., a leading provider of warranty/mar...",None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
2,None,Reliable Software is looking for Jr. Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
3,None,"$95,000 - $120,000 a yearSapphire Digital is l...",95000 - 120000,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,95000,120000
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
5,AKCEA Therapeutics,"Ionis Pharmaceuticals, Inc., located in the No...",None,Clinical Data Scientist & Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
6,KAYAK,Position\n\nKAYAK is looking for people who lo...,None,Data Scientist (Labs),https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
7,IStream Solutions,*Duration: Contract to HireBackground: Data An...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0,0
8,NLB Corp,ContractAnalysis of large amounts of historica...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0,0
9,R2 Global AI,"$220,000 - $300,000 a yearPrincipal NLP Data S...",220000 - 300000,"Principle NLP Data Scientist, $220k-$300k, 40%...",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,220000,300000
10,Daimler,Associate Software Engineer\nDescription\n\nMe...,None,Associate Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
11,"NVR, Inc",NVR has been helping families build their happ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
12,The Resource Connection,"$35 an hourTemporaryA state agency in Boston, ...",35,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,35,0
13,Astral Technologies Inc,$70 an hourAstral Techs is searching for a Dat...,70,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,hour,70,0
14,Sperry Rail Inc.,$15 an hourVisual Data AnalystJoin the world l...,15,Visual Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,15,0
15,AMGTech Solutions,"$60,000 - $70,000 a yearAMGTech Solutions is l...",60000 - 70000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000,70000
16,Perfectly Home Rugs,"$66,000 - $71,000 a yearWe are looking for ent...",66000 - 71000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,66000,71000
17,"Transdev Services, Inc.","$85,000 a yearThe Software & Database Speciali...",85000,Transit Software and Database Specialist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,85000,0
18,HCL America,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000,0
19,HCL Americas,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000,0
20,"Terma North America, Inc.","Terma North America (TNA), the US subsidiary o...",None,Windows Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
21,SR Education Group,"$80,000 - $100,000 a yearSR Education Group’s ...",80000 - 100000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,80000,100000
22,HCL Americas,"$60,000 a yearJob Title – Entry Level Software...",60000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000,0
23,Apple,"Summary\nPosted: Apr 2, 2019\nRole Number: 200...",None,"App Store Engineering, Software Engineer",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
24,Sky Highways,If you have 2 or more years software engineeri...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
25,Microsoft,Empower every person and organization on the p...,None,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
26,Dhatronictech,"$67,000 - $75,000 a yearWe have Entry Level So...",67000 - 75000,Entry level Software Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,67000,75000
27,VisionWeb,Position Purpose: VisionWeb is looking for an ...,None,Software Development Engineer in Test,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
28,"Styles Logistics, Inc.",Position Description:We are looking for a Seni...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
29,"Jack Henry and Associates, Inc.",Are you someone who enjoys programming in C# a...,None,C# Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0,0
...,...,...,...,...,...,...,...,...,...,...,...
84,FINTRX,"$50,000 - $65,000 a yearJoin our growing team ...",50000 - 65000,Python Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,year,50000,65000
85,"Bojangles' Restaurants, Inc",We have an opportunity for an experienced and ...,None,Senior Business Insights Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0,0
86,21Tech,$60 - $80 an hourContractWe are looking for a ...,60 - 80,SQL Server Data Warehouse Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,60,80
87,Viola AI,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
88,ANALYTOS,You will collaborate with the brightest techni...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
89,"CICONIX, LLC",Responsibilities and Duties\n\nModeling comple...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
90,Pluralsight,"Job Description\n\nAt Pluralsight, you will be...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
91,Urner Barry,JOB SUMMARY: The Data Scientist is part of the...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
92,The Hartford,Marketing Data Science\n\nThe Hartford seeks a...,None,"Data Scientist, Marketing",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
93,New York City Council,DUTIES AND RESPONSIBILITIESAre you excited by ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
94,Digitas,Job Description\n\nData & Analysis – Data Scie...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
95,Globant,We are a digitally native company where innova...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
96,Better.com,About Better:\nWe're one of the fastest growin...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
97,Reliant Technologies,Junior Data ScientistReliant Technologies is s...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
98,MRP,"$85,000 - $110,000 a yearA D.C. area company w...",85000 - 110000,Sr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000,110000
99,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ub...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
100,"Amazon.com Services, Inc.","Masters in Analytics, Statistics, Operations R...",None,ACES Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
101,Honor,"Founded in 2015, Honor is now one of the faste...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
102,AETNA,POSITION SUMMARY\nPlease only use the job desc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
103,NEOGOV,We are looking for someone that possesses the ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
104,NYC Health + Hospitals,Clinical Data Scientist (Clinical Business Ana...,None,Clinical Data Scientist (Clinical Business Ana...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
105,"Audible, Inc.",Bachelors or MS or PhD in the following discip...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
106,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ma...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
107,Synchrony,"$85,000 - $170,000 a yearJob Description:\nRol...",85000 - 170000,"VP, Data Scientist",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000,170000
108,Cengage,.\nDo you dare to reinvent the future of educa...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
109,Global Widget LLC (local Tampa Bay candidates ...,"$80,000 - $90,000 a yearData Scientist - Excel...",80000 - 90000,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,80000,90000
110,FPT Software,Requires an extensive Data Science Education a...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
111,Medal,Welcome to MEDAL! We're making it easy to shar...,None,BioMedical Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
112,"Amazon.com Services, Inc.","Master's Degree in Computer Science, Mathemati...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0
113,American Institutes for Research,Overview\nWe are looking for a data scientist ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0,0

In [17]:
df['salary_lower'] = pd.to_numeric(df['salary_lower'])
df['salary_upper'] = pd.to_numeric(df['salary_upper'])
df

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date,salary_period,salary_lower,salary_upper
0,"After, Inc.","After Inc., a leading provider of warranty/mar...",None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
2,None,Reliable Software is looking for Jr. Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
3,None,"$95,000 - $120,000 a yearSapphire Digital is l...",95000 - 120000,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,95000.0,120000.0
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
5,AKCEA Therapeutics,"Ionis Pharmaceuticals, Inc., located in the No...",None,Clinical Data Scientist & Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
6,KAYAK,Position\n\nKAYAK is looking for people who lo...,None,Data Scientist (Labs),https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
7,IStream Solutions,*Duration: Contract to HireBackground: Data An...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0
8,NLB Corp,ContractAnalysis of large amounts of historica...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0
9,R2 Global AI,"$220,000 - $300,000 a yearPrincipal NLP Data S...",220000 - 300000,"Principle NLP Data Scientist, $220k-$300k, 40%...",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,220000.0,300000.0
10,Daimler,Associate Software Engineer\nDescription\n\nMe...,None,Associate Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
11,"NVR, Inc",NVR has been helping families build their happ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
12,The Resource Connection,"$35 an hourTemporaryA state agency in Boston, ...",35,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,35.0,0.0
13,Astral Technologies Inc,$70 an hourAstral Techs is searching for a Dat...,70,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,hour,70.0,0.0
14,Sperry Rail Inc.,$15 an hourVisual Data AnalystJoin the world l...,15,Visual Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,15.0,0.0
15,AMGTech Solutions,"$60,000 - $70,000 a yearAMGTech Solutions is l...",60000 - 70000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,70000.0
16,Perfectly Home Rugs,"$66,000 - $71,000 a yearWe are looking for ent...",66000 - 71000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,66000.0,71000.0
17,"Transdev Services, Inc.","$85,000 a yearThe Software & Database Speciali...",85000,Transit Software and Database Specialist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,85000.0,0.0
18,HCL America,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0
19,HCL Americas,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0
20,"Terma North America, Inc.","Terma North America (TNA), the US subsidiary o...",None,Windows Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
21,SR Education Group,"$80,000 - $100,000 a yearSR Education Group’s ...",80000 - 100000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,80000.0,100000.0
22,HCL Americas,"$60,000 a yearJob Title – Entry Level Software...",60000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0
23,Apple,"Summary\nPosted: Apr 2, 2019\nRole Number: 200...",None,"App Store Engineering, Software Engineer",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
24,Sky Highways,If you have 2 or more years software engineeri...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
25,Microsoft,Empower every person and organization on the p...,None,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
26,Dhatronictech,"$67,000 - $75,000 a yearWe have Entry Level So...",67000 - 75000,Entry level Software Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,67000.0,75000.0
27,VisionWeb,Position Purpose: VisionWeb is looking for an ...,None,Software Development Engineer in Test,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
28,"Styles Logistics, Inc.",Position Description:We are looking for a Seni...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
29,"Jack Henry and Associates, Inc.",Are you someone who enjoys programming in C# a...,None,C# Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
84,FINTRX,"$50,000 - $65,000 a yearJoin our growing team ...",50000 - 65000,Python Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,year,50000.0,65000.0
85,"Bojangles' Restaurants, Inc",We have an opportunity for an experienced and ...,None,Senior Business Insights Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0
86,21Tech,$60 - $80 an hourContractWe are looking for a ...,60 - 80,SQL Server Data Warehouse Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,60.0,80.0
87,Viola AI,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
88,ANALYTOS,You will collaborate with the brightest techni...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
89,"CICONIX, LLC",Responsibilities and Duties\n\nModeling comple...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
90,Pluralsight,"Job Description\n\nAt Pluralsight, you will be...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
91,Urner Barry,JOB SUMMARY: The Data Scientist is part of the...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
92,The Hartford,Marketing Data Science\n\nThe Hartford seeks a...,None,"Data Scientist, Marketing",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
93,New York City Council,DUTIES AND RESPONSIBILITIESAre you excited by ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
94,Digitas,Job Description\n\nData & Analysis – Data Scie...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
95,Globant,We are a digitally native company where innova...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
96,Better.com,About Better:\nWe're one of the fastest growin...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
97,Reliant Technologies,Junior Data ScientistReliant Technologies is s...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
98,MRP,"$85,000 - $110,000 a yearA D.C. area company w...",85000 - 110000,Sr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000.0,110000.0
99,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ub...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
100,"Amazon.com Services, Inc.","Masters in Analytics, Statistics, Operations R...",None,ACES Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
101,Honor,"Founded in 2015, Honor is now one of the faste...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
102,AETNA,POSITION SUMMARY\nPlease only use the job desc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
103,NEOGOV,We are looking for someone that possesses the ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
104,NYC Health + Hospitals,Clinical Data Scientist (Clinical Business Ana...,None,Clinical Data Scientist (Clinical Business Ana...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
105,"Audible, Inc.",Bachelors or MS or PhD in the following discip...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
106,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ma...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
107,Synchrony,"$85,000 - $170,000 a yearJob Description:\nRol...",85000 - 170000,"VP, Data Scientist",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000.0,170000.0
108,Cengage,.\nDo you dare to reinvent the future of educa...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
109,Global Widget LLC (local Tampa Bay candidates ...,"$80,000 - $90,000 a yearData Scientist - Excel...",80000 - 90000,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,80000.0,90000.0
110,FPT Software,Requires an extensive Data Science Education a...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
111,Medal,Welcome to MEDAL! We're making it easy to shar...,None,BioMedical Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
112,"Amazon.com Services, Inc.","Master's Degree in Computer Science, Mathemati...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0
113,American Institutes for Research,Overview\nWe are looking for a data scientist ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0

In [18]:
df.loc[df['salary_period'] == 'month','salary_lower'] = df['salary_lower']*12
df.loc[df['salary_period'] == 'month','salary_upper'] = df['salary_upper']*12
df.loc[df['salary_period'] == 'week','salary_lower'] = df['salary_lower']*52
df.loc[df['salary_period'] == 'week','salary_upper'] = df['salary_upper']*52
df.loc[df['salary_period'] == 'day','salary_lower'] = df['salary_lower']*260
df.loc[df['salary_period'] == 'day','salary_upper'] = df['salary_upper']*260
df.loc[df['salary_period'] == 'hour','salary_lower'] = df['salary_lower']*2080
df.loc[df['salary_period'] == 'hour','salary_upper'] = df['salary_upper']*2080

In [19]:
df['salary_average'] = np.where(df['salary_lower'] == 0, df['salary_upper'], (np.where(df['salary_upper'] == 0, df['salary_lower'], (df['salary_lower']+ df['salary_lower'])/2)))

In [20]:
df

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date,salary_period,salary_lower,salary_upper,salary_average
0,"After, Inc.","After Inc., a leading provider of warranty/mar...",None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
2,None,Reliable Software is looking for Jr. Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
3,None,"$95,000 - $120,000 a yearSapphire Digital is l...",95000 - 120000,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,95000.0,120000.0,95000.0
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
5,AKCEA Therapeutics,"Ionis Pharmaceuticals, Inc., located in the No...",None,Clinical Data Scientist & Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
6,KAYAK,Position\n\nKAYAK is looking for people who lo...,None,Data Scientist (Labs),https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
7,IStream Solutions,*Duration: Contract to HireBackground: Data An...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0,0.0
8,NLB Corp,ContractAnalysis of large amounts of historica...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0,0.0
9,R2 Global AI,"$220,000 - $300,000 a yearPrincipal NLP Data S...",220000 - 300000,"Principle NLP Data Scientist, $220k-$300k, 40%...",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,220000.0,300000.0,220000.0
10,Daimler,Associate Software Engineer\nDescription\n\nMe...,None,Associate Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
11,"NVR, Inc",NVR has been helping families build their happ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
12,The Resource Connection,"$35 an hourTemporaryA state agency in Boston, ...",35,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,72800.0,0.0,72800.0
13,Astral Technologies Inc,$70 an hourAstral Techs is searching for a Dat...,70,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,hour,145600.0,0.0,145600.0
14,Sperry Rail Inc.,$15 an hourVisual Data AnalystJoin the world l...,15,Visual Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,31200.0,0.0,31200.0
15,AMGTech Solutions,"$60,000 - $70,000 a yearAMGTech Solutions is l...",60000 - 70000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,70000.0,60000.0
16,Perfectly Home Rugs,"$66,000 - $71,000 a yearWe are looking for ent...",66000 - 71000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,66000.0,71000.0,66000.0
17,"Transdev Services, Inc.","$85,000 a yearThe Software & Database Speciali...",85000,Transit Software and Database Specialist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,85000.0,0.0,85000.0
18,HCL America,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0,60000.0
19,HCL Americas,"$60,000 a yearJob SummaryPosition: Software En...",60000,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0,60000.0
20,"Terma North America, Inc.","Terma North America (TNA), the US subsidiary o...",None,Windows Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
21,SR Education Group,"$80,000 - $100,000 a yearSR Education Group’s ...",80000 - 100000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,80000.0,100000.0,80000.0
22,HCL Americas,"$60,000 a yearJob Title – Entry Level Software...",60000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0,60000.0
23,Apple,"Summary\nPosted: Apr 2, 2019\nRole Number: 200...",None,"App Store Engineering, Software Engineer",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
24,Sky Highways,If you have 2 or more years software engineeri...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
25,Microsoft,Empower every person and organization on the p...,None,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
26,Dhatronictech,"$67,000 - $75,000 a yearWe have Entry Level So...",67000 - 75000,Entry level Software Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,67000.0,75000.0,67000.0
27,VisionWeb,Position Purpose: VisionWeb is looking for an ...,None,Software Development Engineer in Test,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
28,"Styles Logistics, Inc.",Position Description:We are looking for a Seni...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
29,"Jack Henry and Associates, Inc.",Are you someone who enjoys programming in C# a...,None,C# Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
84,FINTRX,"$50,000 - $65,000 a yearJoin our growing team ...",50000 - 65000,Python Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,year,50000.0,65000.0,50000.0
85,"Bojangles' Restaurants, Inc",We have an opportunity for an experienced and ...,None,Senior Business Insights Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0,0.0
86,21Tech,$60 - $80 an hourContractWe are looking for a ...,60 - 80,SQL Server Data Warehouse Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,124800.0,166400.0,124800.0
87,Viola AI,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
88,ANALYTOS,You will collaborate with the brightest techni...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
89,"CICONIX, LLC",Responsibilities and Duties\n\nModeling comple...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
90,Pluralsight,"Job Description\n\nAt Pluralsight, you will be...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
91,Urner Barry,JOB SUMMARY: The Data Scientist is part of the...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
92,The Hartford,Marketing Data Science\n\nThe Hartford seeks a...,None,"Data Scientist, Marketing",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
93,New York City Council,DUTIES AND RESPONSIBILITIESAre you excited by ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
94,Digitas,Job Description\n\nData & Analysis – Data Scie...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
95,Globant,We are a digitally native company where innova...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
96,Better.com,About Better:\nWe're one of the fastest growin...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
97,Reliant Technologies,Junior Data ScientistReliant Technologies is s...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
98,MRP,"$85,000 - $110,000 a yearA D.C. area company w...",85000 - 110000,Sr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000.0,110000.0,85000.0
99,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ub...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
100,"Amazon.com Services, Inc.","Masters in Analytics, Statistics, Operations R...",None,ACES Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
101,Honor,"Founded in 2015, Honor is now one of the faste...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
102,AETNA,POSITION SUMMARY\nPlease only use the job desc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
103,NEOGOV,We are looking for someone that possesses the ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
104,NYC Health + Hospitals,Clinical Data Scientist (Clinical Business Ana...,None,Clinical Data Scientist (Clinical Business Ana...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
105,"Audible, Inc.",Bachelors or MS or PhD in the following discip...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
106,Uber,"At Uber, we ignite opportunity by setting the ...",None,2019 University Graduate - Data Scientist - Ma...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
107,Synchrony,"$85,000 - $170,000 a yearJob Description:\nRol...",85000 - 170000,"VP, Data Scientist",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000.0,170000.0,85000.0
108,Cengage,.\nDo you dare to reinvent the future of educa...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
109,Global Widget LLC (local Tampa Bay candidates ...,"$80,000 - $90,000 a yearData Scientist - Excel...",80000 - 90000,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,80000.0,90000.0,80000.0
110,FPT Software,Requires an extensive Data Science Education a...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
111,Medal,Welcome to MEDAL! We're making it easy to shar...,None,BioMedical Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
112,"Amazon.com Services, Inc.","Master's Degree in Computer Science, Mathemati...",None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
113,American Institutes for Research,Overview\nWe are looking for a data scientist ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0

In [21]:
df_json = df.to_json(orient='records')
df_json
print(type(df_json))
with open('df_json.json','a') as file:
    json.dump(df_json,file)

<class 'str'>

In [22]:
def data_clean(df, column):
    cleaning_list = ['+','$','/',',','?','.',';','-','@','!','&','%','^','*',')','(','\n']
    for item in cleaning_list:
        df[column] = df[column].astype(str).str.replace(item, " ")

In [23]:
for column in df.columns[1:2]:
    data_clean(df, column)

In [24]:
df

,company,job_posting_desc,job_posting_salary,job_posting_title,job_posting_url,job_title,location,scrap_date,salary_period,salary_lower,salary_upper,salary_average
0,"After, Inc.",After Inc a leading provider of warranty mar...,None,Statistician / Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
1,None,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
2,None,Reliable Software is looking for Jr Data Scie...,None,Jr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
3,None,95 000 120 000 a yearSapphire Digital is l...,95000 - 120000,BI Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,95000.0,120000.0,95000.0
4,None,Developing database solutions to store and ret...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
5,AKCEA Therapeutics,Ionis Pharmaceuticals Inc located in the No...,None,Clinical Data Scientist & Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
6,KAYAK,Position KAYAK is looking for people who love...,None,Data Scientist (Labs),https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
7,IStream Solutions,Duration: Contract to HireBackground: Data An...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0,0.0
8,NLB Corp,ContractAnalysis of large amounts of historica...,None,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0,0.0
9,R2 Global AI,220 000 300 000 a yearPrincipal NLP Data S...,220000 - 300000,"Principle NLP Data Scientist, $220k-$300k, 40%...",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,220000.0,300000.0,220000.0
10,Daimler,Associate Software Engineer Description Merce...,None,Associate Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
11,"NVR, Inc",NVR has been helping families build their happ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
12,The Resource Connection,35 an hourTemporaryA state agency in Boston ...,35,Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,72800.0,0.0,72800.0
13,Astral Technologies Inc,70 an hourAstral Techs is searching for a Dat...,70,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,hour,145600.0,0.0,145600.0
14,Sperry Rail Inc.,15 an hourVisual Data AnalystJoin the world l...,15,Visual Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,31200.0,0.0,31200.0
15,AMGTech Solutions,60 000 70 000 a yearAMGTech Solutions is l...,60000 - 70000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,70000.0,60000.0
16,Perfectly Home Rugs,66 000 71 000 a yearWe are looking for ent...,66000 - 71000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,66000.0,71000.0,66000.0
17,"Transdev Services, Inc.",85 000 a yearThe Software Database Speciali...,85000,Transit Software and Database Specialist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,85000.0,0.0,85000.0
18,HCL America,60 000 a yearJob SummaryPosition: Software En...,60000,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0,60000.0
19,HCL Americas,60 000 a yearJob SummaryPosition: Software En...,60000,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0,60000.0
20,"Terma North America, Inc.",Terma North America TNA the US subsidiary o...,None,Windows Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
21,SR Education Group,80 000 100 000 a yearSR Education Group’s ...,80000 - 100000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,80000.0,100000.0,80000.0
22,HCL Americas,60 000 a yearJob Title – Entry Level Software...,60000,Entry Level Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,60000.0,0.0,60000.0
23,Apple,Summary Posted: Apr 2 2019 Role Number: 20005...,None,"App Store Engineering, Software Engineer",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
24,Sky Highways,If you have 2 or more years software engineeri...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
25,Microsoft,Empower every person and organization on the p...,None,Software Engineer I,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
26,Dhatronictech,67 000 75 000 a yearWe have Entry Level So...,67000 - 75000,Entry level Software Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,year,67000.0,75000.0,67000.0
27,VisionWeb,Position Purpose: VisionWeb is looking for an ...,None,Software Development Engineer in Test,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
28,"Styles Logistics, Inc.",Position Description:We are looking for a Seni...,None,Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
29,"Jack Henry and Associates, Inc.",Are you someone who enjoys programming in C# a...,None,C# Software Engineer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,software engineer,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
84,FINTRX,50 000 65 000 a yearJoin our growing team ...,50000 - 65000,Python Data Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,year,50000.0,65000.0,50000.0
85,"Bojangles' Restaurants, Inc",We have an opportunity for an experienced and ...,None,Senior Business Insights Analyst,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,None,0.0,0.0,0.0
86,21Tech,60 80 an hourContractWe are looking for a ...,60 - 80,SQL Server Data Warehouse Developer,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data analyst,"San Francisco, CA",03-04-2019,hour,124800.0,166400.0,124800.0
87,Viola AI,Viola AI is looking for experts in data scienc...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
88,ANALYTOS,You will collaborate with the brightest techni...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
89,"CICONIX, LLC",Responsibilities and Duties Modeling complex ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
90,Pluralsight,Job Description At Pluralsight you will be p...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
91,Urner Barry,JOB SUMMARY: The Data Scientist is part of the...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
92,The Hartford,Marketing Data Science The Hartford seeks a t...,None,"Data Scientist, Marketing",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
93,New York City Council,DUTIES AND RESPONSIBILITIESAre you excited by ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
94,Digitas,Job Description Data Analysis – Data Scient...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
95,Globant,We are a digitally native company where innova...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
96,Better.com,About Better: We're one of the fastest growing...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
97,Reliant Technologies,Junior Data ScientistReliant Technologies is s...,None,Junior Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
98,MRP,85 000 110 000 a yearA D C area company w...,85000 - 110000,Sr. Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000.0,110000.0,85000.0
99,Uber,At Uber we ignite opportunity by setting the ...,None,2019 University Graduate - Data Scientist - Ub...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
100,"Amazon.com Services, Inc.",Masters in Analytics Statistics Operations R...,None,ACES Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
101,Honor,Founded in 2015 Honor is now one of the faste...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
102,AETNA,POSITION SUMMARY Please only use the job descr...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
103,NEOGOV,We are looking for someone that possesses the ...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
104,NYC Health + Hospitals,Clinical Data Scientist Clinical Business Ana...,None,Clinical Data Scientist (Clinical Business Ana...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
105,"Audible, Inc.",Bachelors or MS or PhD in the following discip...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
106,Uber,At Uber we ignite opportunity by setting the ...,None,2019 University Graduate - Data Scientist - Ma...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
107,Synchrony,85 000 170 000 a yearJob Description: Role...,85000 - 170000,"VP, Data Scientist",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,85000.0,170000.0,85000.0
108,Cengage,Do you dare to reinvent the future of educat...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
109,Global Widget LLC (local Tampa Bay candidates ...,80 000 90 000 a yearData Scientist Excel...,80000 - 90000,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,year,80000.0,90000.0,80000.0
110,FPT Software,Requires an extensive Data Science Education a...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
111,Medal,Welcome to MEDAL We're making it easy to shar...,None,BioMedical Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
112,"Amazon.com Services, Inc.",Master's Degree in Computer Science Mathemati...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0
113,American Institutes for Research,Overview We are looking for a data scientist t...,None,Data Scientist,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,data scientist,"Boston, MA",03-04-2019,None,0.0,0.0,0.0

In [25]:
df['job_posting_desc'][0]

'After Inc   a leading provider of warranty marketing analytics and technology solutions  is seeking a Statistician to join our team About This Position When you join After Inc  you are joining a firm that brings together marketing  strategy  analytics and technology in a unique package to drive increased profits for our clients  The Statistician will work with our advanced analytics group to deliver statistical analyses and modeling results to our clients QualificationsTo perform this job successfully the candidate must be able to perform each duty satisfactorily  Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions  The requirements listed below are representative of the knowledge  skill  and or ability required:Masters or Phd in Statistics  Applied Math  Econometrics or closely related field 0 3 years work experience  Recent graduates are encouraged to apply A deep understanding of various statistical methods  such as linear and logistic regression  time series  design of experiments  etc  Experience with survival analysis  i e  censored data  is preferred Statistical programming experience: SAS programming and ability to use base SAS and SQL to deal with various analytical and data processing tasks  and or  R programming and ability to use R statistical  reporting and database packages to deal with various analytical and data processing tasksExperience working with large datasets and complex relational data modelsEffective oral and written communication skillsExperience in data mining and direct marketing campaigns is a plusRole and Responsibilities The Statistician will report to a Manager or Director of Analytics and will have a number of important responsibilities  including:Interface with various database platforms to pull data and link them logically  know how to deal with the inherent structure of the data Use SAS and or R to perform standard statistical analysis  profiling  reporting and model implementation Build statistical models  such as linear or logistic regression  survival and other parametric or non parametric models that predict various business metrics Summarize and present results for non technical client audience Work with senior Analytics personnel to develop new methods for statistical analysis and visualization Candidates not local to the area must be willing to relocate  Competitive salary and benefits based on experience are offered for this position How to Apply Apply at https:  afterinc recruiterbox com  Please include a brief cover letter outlining your qualifications for this position  In your cover letter  describe a recent project  your role  and what value you created on the project Job Type: Full time'

In [26]:
# job description

In [27]:
data = df[['job_posting_desc']]
data.head()

                                    job_posting_desc
0  After Inc   a leading provider of warranty mar...
1  Viola AI is looking for experts in data scienc...
2  Reliable Software is looking for Jr  Data Scie...
3   95 000    120 000 a yearSapphire Digital is l...
4  Developing database solutions to store and ret...

In [28]:
data

                                      job_posting_desc
0    After Inc   a leading provider of warranty mar...
1    Viola AI is looking for experts in data scienc...
2    Reliable Software is looking for Jr  Data Scie...
3     95 000    120 000 a yearSapphire Digital is l...
4    Developing database solutions to store and ret...
5    Ionis Pharmaceuticals  Inc   located in the No...
6    Position  KAYAK is looking for people who love...
7     Duration: Contract to HireBackground: Data An...
8    ContractAnalysis of large amounts of historica...
9     220 000    300 000 a yearPrincipal NLP Data S...
10   Associate Software Engineer Description  Merce...
11   NVR has been helping families build their happ...
12    35 an hourTemporaryA state agency in Boston  ...
13    70 an hourAstral Techs is searching for a Dat...
14    15 an hourVisual Data AnalystJoin the world l...
15    60 000    70 000 a yearAMGTech Solutions is l...
16    66 000    71 000 a yearWe are looking for ent...
17    85 000 a yearThe Software   Database Speciali...
18    60 000 a yearJob SummaryPosition: Software En...
19    60 000 a yearJob SummaryPosition: Software En...
20   Terma North America  TNA   the US subsidiary o...
21    80 000    100 000 a yearSR Education Group’s ...
22    60 000 a yearJob Title – Entry Level Software...
23   Summary Posted: Apr 2  2019 Role Number: 20005...
24   If you have 2 or more years software engineeri...
25   Empower every person and organization on the p...
26    67 000    75 000 a yearWe have Entry Level So...
27   Position Purpose: VisionWeb is looking for an ...
28   Position Description:We are looking for a Seni...
29   Are you someone who enjoys programming in C# a...
..                                                 ...
84    50 000    65 000 a yearJoin our growing team ...
85   We have an opportunity for an experienced and ...
86    60    80 an hourContractWe are looking for a ...
87   Viola AI is looking for experts in data scienc...
88   You will collaborate with the brightest techni...
89   Responsibilities and Duties  Modeling complex ...
90   Job Description  At Pluralsight  you will be p...
91   JOB SUMMARY: The Data Scientist is part of the...
92   Marketing Data Science  The Hartford seeks a t...
93   DUTIES AND RESPONSIBILITIESAre you excited by ...
94   Job Description  Data   Analysis – Data Scient...
95   We are a digitally native company where innova...
96   About Better: We're one of the fastest growing...
97   Junior Data ScientistReliant Technologies is s...
98    85 000    110 000 a yearA D C  area company w...
99   At Uber  we ignite opportunity by setting the ...
100  Masters in Analytics  Statistics  Operations R...
101  Founded in 2015  Honor is now one of the faste...
102  POSITION SUMMARY Please only use the job descr...
103  We are looking for someone that possesses the ...
104  Clinical Data Scientist  Clinical Business Ana...
105  Bachelors or MS or PhD in the following discip...
106  At Uber  we ignite opportunity by setting the ...
107   85 000    170 000 a yearJob Description: Role...
108    Do you dare to reinvent the future of educat...
109   80 000    90 000 a yearData Scientist   Excel...
110  Requires an extensive Data Science Education a...
111  Welcome to MEDAL  We're making it easy to shar...
112  Master's Degree in Computer Science  Mathemati...
113  Overview We are looking for a data scientist t...

[114 rows x 1 columns]

In [29]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
import string
from nltk.corpus import stopwords

In [32]:
# nltk.download()

In [30]:
for desc in data['job_posting_desc']:
    desc = desc.replace('\n','')
    desc = desc.replace('\\n','')
    desc = desc.translate(str.maketrans('', '', string.punctuation))
data.head()

                                      job_posting_desc
0    After Inc   a leading provider of warranty mar...
1    Viola AI is looking for experts in data scienc...
2    Reliable Software is looking for Jr  Data Scie...
3     95 000    120 000 a yearSapphire Digital is l...
4    Developing database solutions to store and ret...
5    Ionis Pharmaceuticals  Inc   located in the No...
6    Position  KAYAK is looking for people who love...
7     Duration: Contract to HireBackground: Data An...
8    ContractAnalysis of large amounts of historica...
9     220 000    300 000 a yearPrincipal NLP Data S...
10   Associate Software Engineer Description  Merce...
11   NVR has been helping families build their happ...
12    35 an hourTemporaryA state agency in Boston  ...
13    70 an hourAstral Techs is searching for a Dat...
14    15 an hourVisual Data AnalystJoin the world l...
15    60 000    70 000 a yearAMGTech Solutions is l...
16    66 000    71 000 a yearWe are looking for ent...
17    85 000 a yearThe Software   Database Speciali...
18    60 000 a yearJob SummaryPosition: Software En...
19    60 000 a yearJob SummaryPosition: Software En...
20   Terma North America  TNA   the US subsidiary o...
21    80 000    100 000 a yearSR Education Group’s ...
22    60 000 a yearJob Title – Entry Level Software...
23   Summary Posted: Apr 2  2019 Role Number: 20005...
24   If you have 2 or more years software engineeri...
25   Empower every person and organization on the p...
26    67 000    75 000 a yearWe have Entry Level So...
27   Position Purpose: VisionWeb is looking for an ...
28   Position Description:We are looking for a Seni...
29   Are you someone who enjoys programming in C# a...
..                                                 ...
84    50 000    65 000 a yearJoin our growing team ...
85   We have an opportunity for an experienced and ...
86    60    80 an hourContractWe are looking for a ...
87   Viola AI is looking for experts in data scienc...
88   You will collaborate with the brightest techni...
89   Responsibilities and Duties  Modeling complex ...
90   Job Description  At Pluralsight  you will be p...
91   JOB SUMMARY: The Data Scientist is part of the...
92   Marketing Data Science  The Hartford seeks a t...
93   DUTIES AND RESPONSIBILITIESAre you excited by ...
94   Job Description  Data   Analysis – Data Scient...
95   We are a digitally native company where innova...
96   About Better: We're one of the fastest growing...
97   Junior Data ScientistReliant Technologies is s...
98    85 000    110 000 a yearA D C  area company w...
99   At Uber  we ignite opportunity by setting the ...
100  Masters in Analytics  Statistics  Operations R...
101  Founded in 2015  Honor is now one of the faste...
102  POSITION SUMMARY Please only use the job descr...
103  We are looking for someone that possesses the ...
104  Clinical Data Scientist  Clinical Business Ana...
105  Bachelors or MS or PhD in the following discip...
106  At Uber  we ignite opportunity by setting the ...
107   85 000    170 000 a yearJob Description: Role...
108    Do you dare to reinvent the future of educat...
109   80 000    90 000 a yearData Scientist   Excel...
110  Requires an extensive Data Science Education a...
111  Welcome to MEDAL  We're making it easy to shar...
112  Master's Degree in Computer Science  Mathemati...
113  Overview We are looking for a data scientist t...

[114 rows x 1 columns]

In [31]:
stopWords = set(stopwords.words('english'))
data['job_desc'] = data['job_posting_desc'].str.lower().str.split()
data['job_desc'] = data['job_desc'].apply(lambda x : [item for item in x if item not in stopWords])
data

C:\Users\menit\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\menit\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,job_posting_desc,job_desc
0,After Inc a leading provider of warranty mar...,"[inc, leading, provider, warranty, marketing, ..."
1,Viola AI is looking for experts in data scienc...,"[viola, ai, looking, experts, data, science, m..."
2,Reliable Software is looking for Jr Data Scie...,"[reliable, software, looking, jr, data, scient..."
3,95 000 120 000 a yearSapphire Digital is l...,"[95, 000, 120, 000, yearsapphire, digital, loo..."
4,Developing database solutions to store and ret...,"[developing, database, solutions, store, retri..."
5,Ionis Pharmaceuticals Inc located in the No...,"[ionis, pharmaceuticals, inc, located, north, ..."
6,Position KAYAK is looking for people who love...,"[position, kayak, looking, people, love, worki..."
7,Duration: Contract to HireBackground: Data An...,"[duration:, contract, hirebackground:, data, a..."
8,ContractAnalysis of large amounts of historica...,"[contractanalysis, large, amounts, historical,..."
9,220 000 300 000 a yearPrincipal NLP Data S...,"[220, 000, 300, 000, yearprincipal, nlp, data,..."
10,Associate Software Engineer Description Merce...,"[associate, software, engineer, description, m..."
11,NVR has been helping families build their happ...,"[nvr, helping, families, build, happily, ever,..."
12,35 an hourTemporaryA state agency in Boston ...,"[35, hourtemporarya, state, agency, boston, se..."
13,70 an hourAstral Techs is searching for a Dat...,"[70, hourastral, techs, searching, data, scien..."
14,15 an hourVisual Data AnalystJoin the world l...,"[15, hourvisual, data, analystjoin, world, lea..."
15,60 000 70 000 a yearAMGTech Solutions is l...,"[60, 000, 70, 000, yearamgtech, solutions, loo..."
16,66 000 71 000 a yearWe are looking for ent...,"[66, 000, 71, 000, yearwe, looking, entry, lev..."
17,85 000 a yearThe Software Database Speciali...,"[85, 000, yearthe, software, database, special..."
18,60 000 a yearJob SummaryPosition: Software En...,"[60, 000, yearjob, summaryposition:, software,..."
19,60 000 a yearJob SummaryPosition: Software En...,"[60, 000, yearjob, summaryposition:, software,..."
20,Terma North America TNA the US subsidiary o...,"[terma, north, america, tna, us, subsidiary, d..."
21,80 000 100 000 a yearSR Education Group’s ...,"[80, 000, 100, 000, yearsr, education, group’s..."
22,60 000 a yearJob Title – Entry Level Software...,"[60, 000, yearjob, title, –, entry, level, sof..."
23,Summary Posted: Apr 2 2019 Role Number: 20005...,"[summary, posted:, apr, 2, 2019, role, number:..."
24,If you have 2 or more years software engineeri...,"[2, years, software, engineering, experience, ..."
25,Empower every person and organization on the p...,"[empower, every, person, organization, planet,..."
26,67 000 75 000 a yearWe have Entry Level So...,"[67, 000, 75, 000, yearwe, entry, level, softw..."
27,Position Purpose: VisionWeb is looking for an ...,"[position, purpose:, visionweb, looking, outst..."
28,Position Description:We are looking for a Seni...,"[position, description:we, looking, senior, fu..."
29,Are you someone who enjoys programming in C# a...,"[someone, enjoys, programming, c#, solving, co..."
...,...,...
84,50 000 65 000 a yearJoin our growing team ...,"[50, 000, 65, 000, yearjoin, growing, team, pa..."
85,We have an opportunity for an experienced and ...,"[opportunity, experienced, energetic, senior, ..."
86,60 80 an hourContractWe are looking for a ...,"[60, 80, hourcontractwe, looking, microsoft, s..."
87,Viola AI is looking for experts in data scienc...,"[viola, ai, looking, experts, data, science, m..."
88,You will collaborate with the brightest techni...,"[collaborate, brightest, technical, minds, bui..."
89,Responsibilities and Duties Modeling complex ...,"[responsibilities, duties, modeling, complex, ..."
90,Job Description At Pluralsight you will be p...,"[job, description, pluralsight, part, establis..."
91,JOB SUMMARY: The Data Scientist is part of the...,"[job, summary:, data, scientist, part, instant..."
92,Marketing Data Science The Hartford seeks a t...,"[marketing, data, science, hartford, seeks, ta..."
93,DUTIES AND RESPONSIBILITIESAre you excited by ...,"[duties, responsibilitiesare, excited, opportu..."
94,Job Description Data Analysis – Data Scient...,"[job, description, data, analysis, –, data, sc..."
95,We are a digitally native company where innova...,"[digitally, native, company, innovation, desig..."
96,About Better: We're one of the fastest growing...,"[better:, we're, one, fastest, growing, homeow..."
97,Junior Data ScientistReliant Technologies is s...,"[junior, data, scientistreliant, technologies,..."
98,85 000 110 000 a yearA D C area company w...,"[85, 000, 110, 000, yeara, c, area, company, r..."
99,At Uber we ignite opportunity by setting the ...,"[uber, ignite, opportunity, setting, world, mo..."
100,Masters in Analytics Statistics Operations R...,"[masters, analytics, statistics, operations, r..."
101,Founded in 2015 Honor is now one of the faste...,"[founded, 2015, honor, one, fastest, growing, ..."
102,POSITION SUMMARY Please only use the job descr...,"[position, summary, please, use, job, descript..."
103,We are looking for someone that possesses the ...,"[looking, someone, possesses, technical, abili..."
104,Clinical Data Scientist Clinical Business Ana...,"[clinical, data, scientist, clinical, business..."
105,Bachelors or MS or PhD in the following discip...,"[bachelors, ms, phd, following, discipline:, c..."
106,At Uber we ignite opportunity by setting the ...,"[uber, ignite, opportunity, setting, world, mo..."
107,85 000 170 000 a yearJob Description: Role...,"[85, 000, 170, 000, yearjob, description:, rol..."
108,Do you dare to reinvent the future of educat...,"[dare, reinvent, future, education, cengage, h..."
109,80 000 90 000 a yearData Scientist Excel...,"[80, 000, 90, 000, yeardata, scientist, excell..."
110,Requires an extensive Data Science Education a...,"[requires, extensive, data, science, education..."
111,Welcome to MEDAL We're making it easy to shar...,"[welcome, medal, we're, making, easy, share, s..."
112,Master's Degree in Computer Science Mathemati...,"[master's, degree, computer, science, mathemat..."
113,Overview We are looking for a data scientist t...,"[overview, looking, data, scientist, join, mac..."

In [31]:
from nltk.tokenize import sent_tokenize, word_tokenize
words = word_tokenize(str1)
sentences = sent_tokenize(str1)

In [32]:
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))
wordsFiltered = []
 
for w in words:
    if w not in stopWords:
        wordsFiltered.append(w)

print(len(stopWords))

179

In [60]:
stopWords = set(stopwords.words('english'))
stopWords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [34]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
for word in wordsFiltered:
    print(ps.stem(word))

0
after
inc
lead
provid
warranti
mar1
viola
AI
look
expert
data
scienc2
reliabl
softwar
look
Jr
data
scie3
95
000
120
000
yearsapphir
digit
l4
develop
databas
solut
store
ret5
ioni
pharmaceut
inc
locat
no6
posit
kayak
look
peopl
love7
durat
contract
hirebackground
data
an8
contractanalysi
larg
amount
historica9
220
000
300
000
yearprincip
nlp
data
s10
associ
softwar
engin
descript
merce11
nvr
help
famili
build
happ12
35
hourtemporarya
state
agenc
boston
13
70
hourastr
tech
search
dat14
15
hourvisu
data
analystjoin
world
l15
60
000
70
000
yearamgtech
solut
l16
66
000
71
000
yearw
look
ent17
85
000
yearth
softwar
databas
speciali18
60
000
yearjob
summaryposit
softwar
en19
60
000
yearjob
summaryposit
softwar
en20
terma
north
america
tna
US
subsidiari
o21
80
000
100
000
yearsr
educ
group
’
22
60
000
yearjob
titl
–
entri
level
software23
summari
post
apr
2
2019
role
number
2000524
If
2
year
softwar
engineeri25
empow
everi
person
organ
p26
67
000
75
000
yearw
entri
level
so27
posit
purpos
visionweb
look
28
posit
descriptionw
look
seni29
are
someon
enjoy
program
C
a30
about
the
positionagili
system
search
31
We
design
engin
firm
corvallis32
thi
full
time
posit
work
ro33
60
000
yearjob
summaryjob
summaryhcl
americ34
posit
softwar
engin
compani
nexleaf
a35
requisit
number154471
locationorlando
dat36
70
000
yearabout
uscompris
nearli
60
037
50
000
75
000
yearat
ordercount
bel38
were
look
peopl
leader39
As
softwar
engin
work
part
o40
75
000
175
000
yearsalari
commensur
41
summari
post
apr
1
2019
weekli
hour
40
r42
59
50
63
75
hourcerebr
group
llc
43
120
000
170
000
yearsoftwar
engin
sa44
54
000
58
000
yearcar
No
matter
45
new
horizon
offer
excel
opportun
t46
70
000
90
000
yearoptomi
partnership47
47
250
yearpay
rang
begin
47
250
26
a48
25
hourinternshipposit
sumari
arc
lo49
job
descript
the
develop
experi
team50
We
current
seek
softwar
engin
51
At
datasync
technolog
softwar
enginee52
25
28
hourcontractdescript
the
soft53
temporari
internshipour
kasa
product
ser54
100
000
175
000
yearth
financi
watchd55
A
new
technolog
paradigm
emerg
one
wit56
contractpiaggio
fast
forward
pff
hire
a57
full
time
virtual
offic
work
remotehexago58
45
000
50
000
yeartemporaryoverview
thi59
bachelor
’
degre
higher
comput
scienc60
found
josh
harri
david
blitzer
harr61
entri
level
analyst
cambridg
MA
unit
st62
iso
new
england
overse
24
7
oper
of63
ralli
health
put
health
th64
respons
respons
ensur
65
who
At
criteo
build
adve66
boyd
caton
group
bcg
inc
seek
full67
55
000
68
800
yearrespons
the
68
60
000
yeartravel
transport
one
69
are
passion
cyber
secur
ch70
washington
DC
occasion
travel
laur71
50
000
60
000
yearjob
summari
the
juveni72
temporarydescript
job
descript
creat
73
At
uber
ignit
opportun
set
74
about
great
oak
charter
school
the
great
oak75
job
summari
the
data
analyst
first
po76
data
analyst
industri
infrastructur
atl77
job
descript
summari
statement
usaid
remai78
doe
idea
fast
pace
continu
evo79
As
data
scientist
core
team
m80
job
descript
analyst
–
data
analysi
dig81
for
decad
asembia
worki82
job
descript
analyst
–
data
analysi
dig83
12
14
hourdata
entri
case
analysttig
ri84
50
000
65
000
yearjoin
grow
team
85
We
opportun
experienc
86
60
80
hourcontractw
look
87
viola
AI
look
expert
data
scienc88
you
collabor
brightest
techni89
respons
duti
model
complex
90
job
descript
At
pluralsight
p91
job
summari
the
data
scientist
part
the92
market
data
scienc
the
hartford
seek
t93
duti
and
responsibilitiesar
excit
94
job
descript
data
analysi
–
data
scient95
We
digit
nativ
compani
innova96
about
better
were
one
fastest
growing97
junior
data
scientistreli
technolog
s98
85
000
110
000
yeara
D
C
area
compani
w99
At
uber
ignit
opportun
set
100
master
analyt
statist
oper
r101
found
2015
honor
one
faste102
posit
summari
pleas
use
job
descr103
We
look
someon
possess
104
clinic
data
scientist
clinic
busi
ana105
bachelor
MS
phd
follow
discip106
At
uber
ignit
opportun
set
107
85
000
170
000
yearjob
descript
role108
Do
dare
reinvent
futur
educat109
80
000
90
000
yeardata
scientist
excel110
requir
extens
data
scienc
educ
a111
welcom
medal
were
make
easi
shar112
master
degre
comput
scienc
mathemati113
overview
We
look
data
scientist

In [35]:
from nltk.tokenize import PunktSentenceTokenizer

for sent in sentences:
    print(nltk.pos_tag(nltk.word_tokenize(sent)))

[('0', 'CD'), ('After', 'IN'), ('Inc', 'NNP'), ('a', 'DT'), ('leading', 'VBG'), ('provider', 'NN'), ('of', 'IN'), ('warranty', 'NN'), ('mar1', 'NN'), ('Viola', 'NNP'), ('AI', 'NNP'), ('is', 'VBZ'), ('looking', 'VBG'), ('for', 'IN'), ('experts', 'NNS'), ('in', 'IN'), ('data', 'NNS'), ('scienc2', 'NNS'), ('Reliable', 'JJ'), ('Software', 'NNP'), ('is', 'VBZ'), ('looking', 'VBG'), ('for', 'IN'), ('Jr', 'NNP'), ('Data', 'NNP'), ('Scie3', 'NNP'), ('95', 'CD'), ('000', 'CD'), ('120', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearSapphire', 'NN'), ('Digital', 'NNP'), ('is', 'VBZ'), ('l4', 'JJ'), ('Developing', 'VBG'), ('database', 'JJ'), ('solutions', 'NNS'), ('to', 'TO'), ('store', 'VB'), ('and', 'CC'), ('ret5', 'VB'), ('Ionis', 'NNP'), ('Pharmaceuticals', 'NNP'), ('Inc', 'NNP'), ('located', 'VBN'), ('in', 'IN'), ('the', 'DT'), ('No6', 'NNP'), ('Position', 'NNP'), ('KAYAK', 'NNP'), ('is', 'VBZ'), ('looking', 'VBG'), ('for', 'IN'), ('people', 'NNS'), ('who', 'WP'), ('love7', 'VBP'), ('Duration', 'NNP'), ('Contract', 'NNP'), ('to', 'TO'), ('HireBackground', 'NNP'), ('Data', 'NNP'), ('An8', 'NNP'), ('ContractAnalysis', 'NNP'), ('of', 'IN'), ('large', 'JJ'), ('amounts', 'NNS'), ('of', 'IN'), ('historica9', 'NN'), ('220', 'CD'), ('000', 'CD'), ('300', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearPrincipal', 'JJ'), ('NLP', 'NNP'), ('Data', 'NNP'), ('S10', 'NNP'), ('Associate', 'NNP'), ('Software', 'NNP'), ('Engineer', 'NNP'), ('Description', 'NNP'), ('Merce11', 'NNP'), ('NVR', 'NNP'), ('has', 'VBZ'), ('been', 'VBN'), ('helping', 'VBG'), ('families', 'NNS'), ('build', 'VBP'), ('their', 'PRP$'), ('happ12', 'NN'), ('35', 'CD'), ('an', 'DT'), ('hourTemporaryA', 'NN'), ('state', 'NN'), ('agency', 'NN'), ('in', 'IN'), ('Boston', 'NNP'), ('13', 'CD'), ('70', 'CD'), ('an', 'DT'), ('hourAstral', 'JJ'), ('Techs', 'NNP'), ('is', 'VBZ'), ('searching', 'VBG'), ('for', 'IN'), ('a', 'DT'), ('Dat14', 'NNP'), ('15', 'CD'), ('an', 'DT'), ('hourVisual', 'JJ'), ('Data', 'NNP'), ('AnalystJoin', 'NNP'), ('the', 'DT'), ('world', 'NN'), ('l15', 'VBZ'), ('60', 'CD'), ('000', 'CD'), ('70', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearAMGTech', 'JJ'), ('Solutions', 'NNP'), ('is', 'VBZ'), ('l16', 'JJ'), ('66', 'CD'), ('000', 'CD'), ('71', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearWe', 'NN'), ('are', 'VBP'), ('looking', 'VBG'), ('for', 'IN'), ('ent17', 'JJ'), ('85', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearThe', 'NN'), ('Software', 'NNP'), ('Database', 'NNP'), ('Speciali18', 'NNP'), ('60', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJob', 'NN'), ('SummaryPosition', 'NNP'), ('Software', 'NNP'), ('En19', 'NNP'), ('60', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJob', 'NN'), ('SummaryPosition', 'NNP'), ('Software', 'NNP'), ('En20', 'NNP'), ('Terma', 'NNP'), ('North', 'NNP'), ('America', 'NNP'), ('TNA', 'NNP'), ('the', 'DT'), ('US', 'NNP'), ('subsidiary', 'NN'), ('o21', 'VBD'), ('80', 'CD'), ('000', 'CD'), ('100', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearSR', 'JJ'), ('Education', 'NNP'), ('Group', 'NNP'), ('’', 'NNP'), ('s', 'VBD'), ('22', 'CD'), ('60', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJob', 'NN'), ('Title', 'NNP'), ('–', 'NNP'), ('Entry', 'NNP'), ('Level', 'NNP'), ('Software23', 'NNP'), ('Summary', 'NNP'), ('Posted', 'VBD'), ('Apr', 'NNP'), ('2', 'CD'), ('2019', 'CD'), ('Role', 'NNP'), ('Number', 'NNP'), ('2000524', 'CD'), ('If', 'IN'), ('you', 'PRP'), ('have', 'VBP'), ('2', 'CD'), ('or', 'CC'), ('more', 'JJR'), ('years', 'NNS'), ('software', 'NN'), ('engineeri25', 'RB'), ('Empower', 'NNP'), ('every', 'DT'), ('person', 'NN'), ('and', 'CC'), ('organization', 'NN'), ('on', 'IN'), ('the', 'DT'), ('p26', 'NN'), ('67', 'CD'), ('000', 'CD'), ('75', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearWe', 'NN'), ('have', 'VBP'), ('Entry', 'NNP'), ('Level', 'NNP'), ('So27', 'NNP'), ('Position', 'NNP'), ('Purpose', 'NNP'), ('VisionWeb', 'NNP'), ('is', 'VBZ'), ('looking', 'VBG'), ('for', 'IN'), ('an', 'DT'), ('28', 'CD'), ('Position', 'NN'), ('DescriptionWe', 'NNP'), ('are', 'VBP'), ('looking', 'VBG'), ('for', 'IN'), ('a', 'DT'), ('Seni29', 'NNP'), ('Are', 'NNP'), ('you', 'PRP'), ('someone', 'NN'), ('who', 'WP'), ('enjoys', 'VBZ'), ('programming', 'VBG'), ('in', 'IN'), ('C', 'NNP'), ('a30', 'NN'), ('ABOUT', 'IN'), ('THE', 'NNP'), ('POSITIONAgilis', 'NNP'), ('Systems', 'NNPS'), ('is', 'VBZ'), ('searching', 'VBG'), ('31', 'CD'), ('We', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('design', 'NN'), ('and', 'CC'), ('engineer', 'NN'), ('firm', 'NN'), ('in', 'IN'), ('Corvallis32', 'NNP'), ('This', 'DT'), ('is', 'VBZ'), ('a', 'DT'), ('full', 'JJ'), ('time', 'NN'), ('position', 'NN'), ('working', 'VBG'), ('at', 'IN'), ('the', 'DT'), ('Ro33', 'NNP'), ('60', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJob', 'NN'), ('SummaryJob', 'NNP'), ('SummaryHCL', 'NNP'), ('Americ34', 'NNP'), ('POSITION', 'NNP'), ('Software', 'NNP'), ('Engineer', 'NNP'), ('Company', 'NNP'), ('Nexleaf', 'NNP'), ('A35', 'NNP'), ('Requisition', 'NNP'), ('Number154471', 'NNP'), ('LocationOrlando', 'NNP'), ('Dat36', 'NNP'), ('70', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearAbout', 'NN'), ('UsComprised', 'VBN'), ('of', 'IN'), ('nearly', 'RB'), ('60', 'CD'), ('037', 'CD'), ('50', 'CD'), ('000', 'CD'), ('75', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearAt', 'NN'), ('OrderCounter', 'NNP'), ('we', 'PRP'), ('bel38', 'VBP'), ('Were', 'WRB'), ('looking', 'VBG'), ('for', 'IN'), ('people', 'NNS'), ('who', 'WP'), ('can', 'MD'), ('be', 'VB'), ('the', 'DT'), ('leader39', 'NN'), ('As', 'IN'), ('a', 'DT'), ('Software', 'NNP'), ('Engineer', 'NNP'), ('you', 'PRP'), ('will', 'MD'), ('work', 'VB'), ('as', 'IN'), ('part', 'NN'), ('o40', 'VBZ'), ('75', 'CD'), ('000', 'CD'), ('175', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearSalary', 'JJ'), ('Commensurate', 'NNP'), ('41', 'CD'), ('Summary', 'NNP'), ('Posted', 'VBD'), ('Apr', 'NNP'), ('1', 'CD'), ('2019', 'CD'), ('Weekly', 'NNP'), ('Hours', 'NNP'), ('40', 'CD'), ('R42', 'NNP'), ('59', 'CD'), ('50', 'CD'), ('63', 'CD'), ('75', 'CD'), ('an', 'DT'), ('hourCerebral', 'JJ'), ('Group', 'NNP'), ('LLC', 'NNP'), ('is', 'VBZ'), ('43', 'CD'), ('120', 'CD'), ('000', 'CD'), ('170', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearSoftware', 'NN'), ('Engineer', 'NNP'), ('Sa44', 'NNP'), ('54', 'CD'), ('000', 'CD'), ('58', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearCare', 'NN'), ('No', 'NNP'), ('matter', 'NN'), ('what', 'WP'), ('45', 'CD'), ('New', 'NNP'), ('Horizons', 'NNP'), ('offers', 'VBZ'), ('an', 'DT'), ('excellent', 'JJ'), ('opportunity', 'NN'), ('t46', 'VBD'), ('70', 'CD'), ('000', 'CD'), ('90', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearOptomi', 'NN'), ('in', 'IN'), ('partnership47', 'NN'), ('47', 'CD'), ('250', 'CD'), ('a', 'DT'), ('yearPay', 'NN'), ('range', 'NN'), ('begins', 'VBZ'), ('at', 'IN'), ('47', 'CD'), ('250', 'CD'), ('26', 'CD'), ('a48', 'NN'), ('25', 'CD'), ('an', 'DT'), ('hourInternshipPosition', 'NN'), ('Sumary', 'NNP'), ('ARC', 'NNP'), ('is', 'VBZ'), ('lo49', 'JJ'), ('Job', 'NNP'), ('Description', 'NNP'), ('The', 'DT'), ('Developer', 'NNP'), ('Experience', 'NNP'), ('team50', 'NN'), ('We', 'PRP'), ('are', 'VBP'), ('currently', 'RB'), ('seeking', 'VBG'), ('a', 'DT'), ('Software', 'NNP'), ('Engineer', 'NNP'), ('51', 'CD'), ('At', 'IN'), ('DataSync', 'NNP'), ('Technologies', 'NNPS'), ('our', 'PRP$'), ('software', 'NN'), ('enginee52', 'VBZ'), ('25', 'CD'), ('28', 'CD'), ('an', 'DT'), ('hourContractDescription', 'NN'), ('The', 'DT'), ('soft53', 'NN'), ('Temporary', 'NNP'), ('InternshipOur', 'NNP'), ('Kasa', 'NNP'), ('products', 'NNS'), ('and', 'CC'), ('ser54', 'VBD'), ('100', 'CD'), ('000', 'CD'), ('175', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearThe', 'JJ'), ('financial', 'JJ'), ('watchd55', 'NN'), ('A', 'DT'), ('new', 'JJ'), ('technology', 'NN'), ('paradigm', 'NN'), ('is', 'VBZ'), ('emerging', 'VBG'), ('one', 'CD'), ('wit56', 'NN'), ('ContractPiaggio', 'NNP'), ('Fast', 'NNP'), ('Forward', 'NNP'), ('PFF', 'NNP'), ('is', 'VBZ'), ('hiring', 'VBG'), ('a57', 'RB'), ('Full', 'NNP'), ('time', 'NN'), ('Virtual', 'NNP'), ('Office', 'NNP'), ('Work', 'NNP'), ('RemoteHexago58', 'NNP'), ('45', 'CD'), ('000', 'CD'), ('50', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearTemporaryOverview', 'NN'), ('Thi59', 'NNP'), ('Bachelor', 'NNP'), ('’', 'NNP'), ('s', 'VBD'), ('degree', 'NN'), ('or', 'CC'), ('higher', 'JJR'), ('in', 'IN'), ('Computer', 'NNP'), ('Scienc60', 'NNP'), ('Founded', 'NNP'), ('by', 'IN'), ('Josh', 'NNP'), ('Harris', 'NNP'), ('and', 'CC'), ('David', 'NNP'), ('Blitzer', 'NNP'), ('Harr61', 'NNP'), ('Entry', 'NNP'), ('Level', 'NNP'), ('Analyst', 'NNP'), ('Cambridge', 'NNP'), ('MA', 'NNP'), ('United', 'NNP'), ('St62', 'NNP'), ('ISO', 'NNP'), ('New', 'NNP'), ('England', 'NNP'), ('oversees', 'VBZ'), ('the', 'DT'), ('24', 'CD'), ('7', 'CD'), ('operation', 'NN'), ('of63', 'PRP'), ('Rally', 'NNP'), ('Health', 'NNP'), ('is', 'VBZ'), ('all', 'DT'), ('about', 'IN'), ('putting', 'VBG'), ('health', 'NN'), ('in', 'IN'), ('th64', 'NN'), ('RESPONSIBILITIES', 'NNP'), ('Responsible', 'NNP'), ('for', 'IN'), ('ensuring', 'VBG'), ('the', 'DT'), ('65', 'CD'), ('Who', 'IN'), ('we', 'PRP'), ('are', 'VBP'), ('At', 'IN'), ('Criteo', 'NNP'), ('we', 'PRP'), ('are', 'VBP'), ('building', 'VBG'), ('the', 'DT'), ('adve66', 'NN'), ('Boyd', 'NNP'), ('Caton', 'NNP'), ('Group', 'NNP'), ('bcg', 'NN'), ('Inc', 'NNP'), ('is', 'VBZ'), ('seeking', 'VBG'), ('a', 'DT'), ('full67', 'NN'), ('55', 'CD'), ('000', 'CD'), ('68', 'CD'), ('800', 'CD'), ('a', 'DT'), ('yearResponsibilities', 'NNS'), ('The', 'DT'), ('68', 'CD'), ('60', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearTravel', 'NN'), ('and', 'CC'), ('Transport', 'NNP'), ('one', 'CD'), ('of', 'IN'), ('the', 'DT'), ('69', 'CD'), ('Are', 'NNP'), ('you', 'PRP'), ('passionate', 'VBP'), ('about', 'IN'), ('cyber', 'NN'), ('and', 'CC'), ('security', 'NN'), ('ch70', 'VBP'), ('Washington', 'NNP'), ('DC', 'NNP'), ('with', 'IN'), ('occasional', 'JJ'), ('travel', 'NN'), ('to', 'TO'), ('Laur71', 'VB'), ('50', 'CD'), ('000', 'CD'), ('60', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJob', 'NN'), ('Summary', 'NNP'), ('The', 'DT'), ('Juveni72', 'NNP'), ('TemporaryDescription', 'NNP'), ('JOB', 'NNP'), ('DESCRIPTION', 'NNP'), ('Creates', 'VBZ'), ('73', 'CD'), ('At', 'IN'), ('Uber', 'NNP'), ('we', 'PRP'), ('ignite', 'VBP'), ('opportunity', 'NN'), ('by', 'IN'), ('setting', 'VBG'), ('the', 'DT'), ('74', 'CD'), ('About', 'IN'), ('Great', 'NNP'), ('Oaks', 'NNPS'), ('Charter', 'NNP'), ('Schools', 'NNP'), ('The', 'DT'), ('Great', 'NNP'), ('Oak75', 'NNP'), ('Job', 'NNP'), ('Summary', 'NNP'), ('The', 'DT'), ('Data', 'NNP'), ('Analyst', 'NNP'), ('is', 'VBZ'), ('the', 'DT'), ('first', 'JJ'), ('po76', 'NN'), ('Data', 'NNP'), ('Analyst', 'NNP'), ('Industry', 'NNP'), ('Infrastructure', 'NNP'), ('Atl77', 'NNP'), ('Job', 'NNP'), ('Description', 'NNP'), ('Summary', 'NNP'), ('Statement', 'NNP'), ('USAID', 'NNP'), ('remai78', 'NN'), ('Does', 'VBZ'), ('the', 'DT'), ('idea', 'NN'), ('of', 'IN'), ('a', 'DT'), ('fast', 'NN'), ('paced', 'VBN'), ('continually', 'RB'), ('evo79', 'JJ'), ('As', 'IN'), ('a', 'DT'), ('Data', 'NNP'), ('Scientist', 'NNP'), ('you', 'PRP'), ('will', 'MD'), ('be', 'VB'), ('a', 'DT'), ('core', 'NN'), ('team', 'NN'), ('m80', 'NN'), ('Job', 'NNP'), ('Description', 'NNP'), ('Analyst', 'NNP'), ('–', 'NNP'), ('Data', 'NNP'), ('Analysis', 'NNP'), ('Dig81', 'NNP'), ('For', 'IN'), ('more', 'JJR'), ('than', 'IN'), ('a', 'DT'), ('decade', 'NN'), ('Asembia', 'NNP'), ('has', 'VBZ'), ('been', 'VBN'), ('worki82', 'JJ'), ('Job', 'NNP'), ('Description', 'NNP'), ('Analyst', 'NNP'), ('–', 'NNP'), ('Data', 'NNP'), ('Analysis', 'NNP'), ('Dig83', 'NNP'), ('12', 'CD'), ('14', 'CD'), ('an', 'DT'), ('hourData', 'NN'), ('Entry', 'NNP'), ('Case', 'NNP'), ('AnalystTIG', 'NNP'), ('Ri84', 'NNP'), ('50', 'CD'), ('000', 'CD'), ('65', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJoin', 'NN'), ('our', 'PRP$'), ('growing', 'VBG'), ('team', 'NN'), ('85', 'CD'), ('We', 'PRP'), ('have', 'VBP'), ('an', 'DT'), ('opportunity', 'NN'), ('for', 'IN'), ('an', 'DT'), ('experienced', 'JJ'), ('and', 'CC'), ('86', 'CD'), ('60', 'CD'), ('80', 'CD'), ('an', 'DT'), ('hourContractWe', 'NN'), ('are', 'VBP'), ('looking', 'VBG'), ('for', 'IN'), ('a', 'DT'), ('87', 'CD'), ('Viola', 'NNP'), ('AI', 'NNP'), ('is', 'VBZ'), ('looking', 'VBG'), ('for', 'IN'), ('experts', 'NNS'), ('in', 'IN'), ('data', 'NNS'), ('scienc88', 'NN'), ('You', 'PRP'), ('will', 'MD'), ('collaborate', 'VB'), ('with', 'IN'), ('the', 'DT'), ('brightest', 'JJS'), ('techni89', 'NN'), ('Responsibilities', 'NNPS'), ('and', 'CC'), ('Duties', 'NNPS'), ('Modeling', 'NNP'), ('complex', 'JJ'), ('90', 'CD'), ('Job', 'NNP'), ('Description', 'NNP'), ('At', 'IN'), ('Pluralsight', 'NNP'), ('you', 'PRP'), ('will', 'MD'), ('be', 'VB'), ('p91', 'JJ'), ('JOB', 'NNP'), ('SUMMARY', 'NNP'), ('The', 'DT'), ('Data', 'NNP'), ('Scientist', 'NNP'), ('is', 'VBZ'), ('part', 'NN'), ('of', 'IN'), ('the92', 'NN'), ('Marketing', 'NNP'), ('Data', 'NNP'), ('Science', 'NNP'), ('The', 'DT'), ('Hartford', 'NNP'), ('seeks', 'VBZ'), ('a', 'DT'), ('t93', 'JJ'), ('DUTIES', 'NNP'), ('AND', 'NNP'), ('RESPONSIBILITIESAre', 'NNP'), ('you', 'PRP'), ('excited', 'VBN'), ('by', 'IN'), ('94', 'CD'), ('Job', 'NNP'), ('Description', 'NNP'), ('Data', 'NNP'), ('Analysis', 'NNP'), ('–', 'NNP'), ('Data', 'NNP'), ('Scient95', 'NNP'), ('We', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('digitally', 'RB'), ('native', 'JJ'), ('company', 'NN'), ('where', 'WRB'), ('innova96', 'NN'), ('About', 'IN'), ('Better', 'JJR'), ('Were', 'NNP'), ('one', 'CD'), ('of', 'IN'), ('the', 'DT'), ('fastest', 'JJS'), ('growing97', 'NN'), ('Junior', 'NNP'), ('Data', 'NNP'), ('ScientistReliant', 'NNP'), ('Technologies', 'NNPS'), ('is', 'VBZ'), ('s98', 'JJ'), ('85', 'CD'), ('000', 'CD'), ('110', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearA', 'NN'), ('D', 'NNP'), ('C', 'NNP'), ('area', 'NN'), ('company', 'NN'), ('w99', 'NN'), ('At', 'IN'), ('Uber', 'NNP'), ('we', 'PRP'), ('ignite', 'VBP'), ('opportunity', 'NN'), ('by', 'IN'), ('setting', 'VBG'), ('the', 'DT'), ('100', 'CD'), ('Masters', 'NNS'), ('in', 'IN'), ('Analytics', 'NNPS'), ('Statistics', 'NNPS'), ('Operations', 'NNPS'), ('R101', 'NNP'), ('Founded', 'NNP'), ('in', 'IN'), ('2015', 'CD'), ('Honor', 'NNP'), ('is', 'VBZ'), ('now', 'RB'), ('one', 'CD'), ('of', 'IN'), ('the', 'DT'), ('faste102', 'JJ'), ('POSITION', 'NNP'), ('SUMMARY', 'NNP'), ('Please', 'NNP'), ('only', 'RB'), ('use', 'VBP'), ('the', 'DT'), ('job', 'NN'), ('descr103', 'NN'), ('We', 'PRP'), ('are', 'VBP'), ('looking', 'VBG'), ('for', 'IN'), ('someone', 'NN'), ('that', 'WDT'), ('possesses', 'VBZ'), ('the', 'DT'), ('104', 'CD'), ('Clinical', 'NNP'), ('Data', 'NNP'), ('Scientist', 'NNP'), ('Clinical', 'NNP'), ('Business', 'NNP'), ('Ana105', 'NNP'), ('Bachelors', 'NNP'), ('or', 'CC'), ('MS', 'NNP'), ('or', 'CC'), ('PhD', 'NNP'), ('in', 'IN'), ('the', 'DT'), ('following', 'JJ'), ('discip106', 'NN'), ('At', 'IN'), ('Uber', 'NNP'), ('we', 'PRP'), ('ignite', 'VBP'), ('opportunity', 'NN'), ('by', 'IN'), ('setting', 'VBG'), ('the', 'DT'), ('107', 'CD'), ('85', 'CD'), ('000', 'CD'), ('170', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearJob', 'NN'), ('Description', 'NNP'), ('Role108', 'NNP'), ('Do', 'NNP'), ('you', 'PRP'), ('dare', 'VB'), ('to', 'TO'), ('reinvent', 'VB'), ('the', 'DT'), ('future', 'NN'), ('of', 'IN'), ('educat109', 'JJ'), ('80', 'CD'), ('000', 'CD'), ('90', 'CD'), ('000', 'CD'), ('a', 'DT'), ('yearData', 'NN'), ('Scientist', 'NNP'), ('Excel110', 'NNP'), ('Requires', 'NNP'), ('an', 'DT'), ('extensive', 'JJ'), ('Data', 'NNP'), ('Science', 'NNP'), ('Education', 'NNP'), ('a111', 'VBZ'), ('Welcome', 'NNP'), ('to', 'TO'), ('MEDAL', 'NNP'), ('Were', 'NNP'), ('making', 'VBG'), ('it', 'PRP'), ('easy', 'JJ'), ('to', 'TO'), ('shar112', 'VB'), ('Masters', 'NNP'), ('Degree', 'NNP'), ('in', 'IN'), ('Computer', 'NNP'), ('Science', 'NNP'), ('Mathemati113', 'NNP'), ('Overview', 'NNP'), ('We', 'PRP'), ('are', 'VBP'), ('looking', 'VBG'), ('for', 'IN'), ('a', 'DT'), ('data', 'NNS'), ('scientist', 'NN'), ('t', 'NN')]